# Generated by Django 5.2.8 on 2025-11-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_billing_amount_due_billing_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='coverage_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash')], max_length=20),
        ),
    ]
