# Generated by Django 5.2.8 on 2025-12-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_appointment_department_alter_billing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
    ]
