# Generated by Django 5.2.8 on 2025-12-26 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_appointment_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='healthresource',
            options={},
        ),
        migrations.RenameField(
            model_name='healthresource',
            old_name='published',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='healthresource',
            name='slug',
        ),
        migrations.AddField(
            model_name='healthresource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthresource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('tip', 'Health Tip')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthresource',
            name='video_url',
            field=models.URLField(blank=True, help_text='Only for video type', null=True),
        ),
        migrations.AlterField(
            model_name='healthresource',
            name='content',
            field=models.TextField(help_text='Article content or Health tip text'),
        ),
        migrations.AddField(
            model_name='healthresource',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='patient.healthcategory'),
            preserve_default=False,
        ),
    ]
