# Generated by Django 5.2.8 on 2025-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_healthcategory_alter_healthresource_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthresource',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='healthresource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('tip', 'Health Tip')], max_length=20),
        ),
    ]
