# Generated by Django 5.2.8 on 2025-11-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EPrescription',
        ),
    ]
