# Generated by Django 5.2.8 on 2025-12-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('doctor', '0002_delete_eprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='admin_panel.department'),
        ),
    ]
