# Generated by Django 5.2.8 on 2025-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
